### ISSUE TITLE
mp4.DecryptSampleCenc <--- Unresolved reference (decrypt.go)

### ISSUE THREAD

**Issue by supercom32** [iyear/gowidevine#14]
Hi,

When I try to run the example program with my own MP4 file, It fails to compile with:

Unresolved reference: mp4.DecryptSampleCenc 

Inside decrypt.go, around line 226.

Was this method omitted from latest code in error?

**Comment by iyear** [comment]
Keep mp4ff version at v0.39.0. After this version, there will be breaking changes.

`go get github.com/Eyevinn/mp4ff@v0.39.0`
